### ISSUE TITLE
Intellisense - Add ParserOptions to Suggest API

### ISSUE THREAD

**Issue by LucGenetier** [microsoft/Power-Fx#533] opened 2022-08-10 08:09 UTC
Need to support AllowSideEffects in Intellisense to avoid "Behavior function in a non-behavior property. You can't use this property to change values elsewhere in the app" error

**Comment by charanm** [comment] 2022-08-10 09:37
Duplicate of #523

**Closed** 2022-08-10 12:05 UTC
